import { useState, type ReactNode } from 'react';
function Brand(){return <a className="brand" href="/" aria-label="SnapERP home"><picture><source media="(prefers-reduced-motion: reduce)" srcSet="/assets/brand/logo-static.png"/><img src="/assets/brand/logo.gif" alt="SnapERP arithmetic tiles" width="48" height="48"/></picture><span>Snap<span className="brand-erp">ERP</span></span></a>}

export function SiteHeader({active=''}:{active?:string}){
 const [menu,setMenu]=useState(false);
 return <><a className="skip-link" href="#main">Skip to content</a><header className="site-header"><div className="header-inner"><Brand/><button className="menu-toggle" aria-expanded={menu} aria-controls="site-nav" onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'}</button><nav id="site-nav" className={menu?'site-nav nav-open':'site-nav'} aria-label="Main navigation">{[['Workflow','/#workflow'],['Features','/features'],['Integrations','/integrations'],['Pricing','/pricing']].map(([label,link])=><a key={label} href={link} aria-current={active===link?'page':undefined} onClick={()=>setMenu(false)}>{label}</a>)}<a className="sign-in" href="https://erp.werevu.co.ke/">Sign in ↗</a><a className="nav-demo" href="/#demo" onClick={()=>setMenu(false)}>Book a demo ↗</a></nav></div></header></>;
}
export function SiteFooter({onPrivacy}:{onPrivacy?:()=>void}){return <footer className="site-footer section-wrap"><div><Brand/><p>Sales, stock and accounts, connected.</p></div><div className="footer-links"><a href="/#workflow">Workflow</a><a href="/features">Features</a><a href="/integrations">Integrations</a><a href="/pricing">Pricing</a><a href="/#security">Security</a>{onPrivacy?<button onClick={onPrivacy}>Demo request privacy</button>:<a href="/#demo">Request a demo</a>}<a href="https://erp.werevu.co.ke/">Sign in ↗</a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} SnapERP</span><span>Follow the goods. Understand the business.</span></div></footer>;}
export function MarketingPage({active,children}:{active:string;children:ReactNode}){return <><SiteHeader active={active}/><main id="main" className="marketing-page">{children}<div className="section-wrap page-demo-link"><a className="nav-demo" href="/#demo">Book a demo ↗</a></div></main><SiteFooter/></>;}
