import { ActionIcon, BusinessIcon } from '@/components/snaperp/site-icons';
import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { MarketingPage } from '@/components/snaperp/site-chrome';

export const Route = createFileRoute('/pricing')({
 head:()=>({meta:[{title:'Pricing | SnapERP'},{name:'description',content:'Build your SnapERP setup and request a tailored quote for modules, users, onboarding and support.'},{property:'og:title',content:'Pricing | SnapERP'},{property:'og:description',content:'Choose the workflows your business needs and discuss a tailored SnapERP setup.'},{property:'og:url',content:'https://bentito.com/pricing'}]}),
 component:Page,
});
const options=['Point of sale','Sales','Purchasing','Inventory','Banking','Accounting & reports','Manufacturing','Fixed assets','Dimensions','M-Pesa','KRA eTIMS'];
const startingPoints=[
 {name:'Connect the essentials',for:'Sales and stock teams',copy:'Bring the everyday movement of goods and customer records together.',modules:['Sales','Purchasing','Inventory','Accounting & reports']},
 {name:'Connect the whole business',for:'Teams working across departments',copy:'Add payment records and discuss the local connections your business needs.',modules:['Sales','Purchasing','Inventory','Banking','Accounting & reports','M-Pesa','KRA eTIMS']},
 {name:'Connect production',for:'Businesses that manufacture',copy:'Discuss the journey from raw materials and work orders to finished stock and sales.',modules:['Sales','Purchasing','Inventory','Banking','Accounting & reports','Manufacturing']},
];
function Page(){
 const [modules,setModules]=useState<string[]>(startingPoints[0].modules);
 const [team,setTeam]=useState('2–5 users'),[onboarding,setOnboarding]=useState('Setup and training'),[support,setSupport]=useState('Discuss support options');
 const toggle=(name:string)=>setModules(current=>current.includes(name)?current.filter(item=>item!==name):[...current,name]);
 const summary=`I would like a quote for SnapERP.\nModules: ${modules.length?modules.join(', '):'Please help me choose'}.\nTeam: ${team}.\nOnboarding: ${onboarding}.\nSupport: ${support}.`;
 const quoteLink=`/?workflow=${encodeURIComponent(summary)}#demo`;
 const choose=(selection:string[])=>{setModules(selection);document.getElementById('configure-setup')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});};
 return <MarketingPage active="/pricing">
  <section className="pricing-hero section-wrap"><p className="feature-kicker">PRICING THAT STARTS WITH YOUR BUSINESS</p><h1>Your workflows.<br/>Your team. Your setup.</h1><p>Choose what you need today. Discuss what comes next. We’ll confirm a quote around your modules, users, onboarding and support.</p><div className="pricing-hero-actions"><a className="nav-demo" href="#configure-setup">Build your setup <ActionIcon name="down"/></a><span>Tailored quote · No payment required to enquire</span></div></section>
  <section className="pricing-start section-wrap" aria-labelledby="starting-heading"><div className="feature-section-heading"><div><p className="feature-kicker">FIND YOUR STARTING POINT</p><h2 id="starting-heading">Start with the work you do.</h2></div><p>These are suggested combinations, not fixed subscription tiers. Adapt any starting point to your business below.</p></div><div className="pricing-start-grid">{startingPoints.map((point)=><article key={point.name}><BusinessIcon name={point.name}/><p className="feature-kicker">{point.for}</p><h3>{point.name}</h3><p>{point.copy}</p><ul>{point.modules.map(module=><li key={module}><ActionIcon name="check"/>{module}</li>)}</ul><button onClick={()=>choose(point.modules)}>Use this starting point <ActionIcon/></button></article>)}</div></section>
  <section className="pricing-config section-wrap" id="configure-setup" aria-labelledby="configure-heading"><div className="feature-section-heading"><div><p className="feature-kicker">MAKE IT YOURS</p><h2 id="configure-heading">Build the brief for your quote.</h2></div><p>Your selections help us understand your needs. Availability, integration requirements and commercial terms will be confirmed together.</p></div><div className="pricing-config-layout"><div className="pricing-config-fields">
   <fieldset className="pricing-module-field"><legend>Which workflows do you need?</legend><p>Select as many as you need, or leave this open for the demo.</p><div className="pricing-module-options">{options.map(name=><label key={name} className={modules.includes(name)?'module-choice is-selected':'module-choice'}><input type="checkbox" checked={modules.includes(name)} onChange={()=>toggle(name)}/><BusinessIcon name={name}/><span>{name}</span></label>)}</div></fieldset>
   <div className="pricing-select-grid"><div><label htmlFor="quote-team">How many people will use it?</label><select id="quote-team" value={team} onChange={event=>setTeam(event.target.value)}>{['1 user','2–5 users','6–15 users','16–50 users','More than 50 users','Help me estimate'].map(value=><option key={value}>{value}</option>)}</select></div><div><label htmlFor="quote-onboarding">How should we help you get started?</label><select id="quote-onboarding" value={onboarding} onChange={event=>setOnboarding(event.target.value)}>{['Setup and training','Setup, data import and training','Discuss a migration','Help me decide'].map(value=><option key={value}>{value}</option>)}</select></div><div><label htmlFor="quote-support">What support would help?</label><select id="quote-support" value={support} onChange={event=>setSupport(event.target.value)}>{['Discuss support options','Initial onboarding support','Ongoing team support'].map(value=><option key={value}>{value}</option>)}</select></div></div>
  </div><aside className="pricing-summary" aria-labelledby="summary-heading"><p className="feature-kicker">YOUR SETUP BRIEF</p><h3 id="summary-heading">Ready for a conversation.</h3><div aria-live="polite" aria-atomic="true"><p className="pricing-module-count"><strong>{modules.length}</strong> {modules.length===1?'workflow selected':'workflows selected'}</p><div className="pricing-summary-tags">{modules.length?modules.map(module=><span key={module}>{module}</span>):<span>We’ll help you choose</span>}</div><dl><div><dt>Team</dt><dd>{team}</dd></div><div><dt>Onboarding</dt><dd>{onboarding}</dd></div><div><dt>Support</dt><dd>{support}</dd></div></dl></div><div className="pricing-quote-label"><span>Pricing</span><strong>Tailored quote</strong><p>We’ll confirm scope and costs before you commit.</p></div><a className="pricing-request" href={quoteLink}>Request my quote <ActionIcon/></a><p className="pricing-summary-note">Your selections carry into the demo request form. Nothing is submitted until you send that form.</p></aside></div></section>
  <section className="pricing-scope section-wrap" aria-labelledby="scope-heading"><div className="feature-section-heading"><div><p className="feature-kicker">KNOW WHAT YOU’RE AGREEING TO</p><h2 id="scope-heading">A clear scope before you start.</h2></div><p>Use your quote discussion to understand the full setup—not just the software modules.</p></div><div className="pricing-scope-grid">{[['Modules & users','Confirm enabled workflows, included users and the cost of additional access.'],['Onboarding & migration','Agree the data to bring across, configuration work, training and responsibilities.'],['Integrations','Confirm supported connections, onboarding requirements and any separate provider charges.'],['Billing & support','Review billing frequency, applicable taxes, support scope and terms for future changes.']].map(([title,copy])=><article key={title}><BusinessIcon name={title}/><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="connection-faq section-wrap" aria-labelledby="pricing-questions"><h2 id="pricing-questions">A few practical questions.</h2>{[['Why isn’t there a fixed price here?','The setup depends on the modules, users, onboarding and support you need. Request a quote so we can confirm the scope and commercial terms for your business.'],['Can I start with fewer modules?','Choose the workflows you want to discuss in the setup builder. We’ll confirm module dependencies and the right starting scope during your demo.'],['Are M-Pesa and eTIMS included automatically?','No automatic inclusion is assumed. Supported modes, onboarding, credentials, availability and any related charges must be confirmed for your setup.'],['Does requesting a quote create a subscription?','No. The form records an enquiry for follow-up. It does not collect payment or create a paid subscription.'],['Can we add more later?','Tell us what you expect to need as you grow. We’ll discuss available expansion options and how changes to scope, users and support would be priced.']].map(([question,answer])=><details key={question}><summary>{question}<ActionIcon name="chevron"/></summary><p>{answer}</p></details>)}</section>
 </MarketingPage>;
}
